### ISSUE TITLE
Unable to pass a msg.payload as a parameter to a Particle Function

### ISSUE THREAD

**Issue by Toby-Mills** [particle-iot/node-red-contrib-particle-official#2]
I might be misunderstanding the Particle Function node, but it appears that the **Argument** property only supports a configured text string, rather than a value passed in as part of the message. Is it possible to rather use something like '_msg.payload_'?

![image](https://user-images.githubusercontent.com/5920505/118607348-c01e2a80-b7b8-11eb-91fd-37bb67450353.png)

**Comment by maxst001** [comment]
Have you yet figured it out how that works?
I'm also not able to send e.g. a string value to a particle device via msg.payload.

**Comment by Toby-Mills** [comment]
> Have you yet figured it out how that works?
> I'm also not able to send e.g. a string value to a particle device via msg.payload.

Nope unfortunately not. I'm going to try just using a straight http request to the particle API, instead of using this library, which is a pity, because it seems to work pretty well otherwise.

**Comment by maxst001** [comment]
Hi Toby,
actually I figured it out yesterday: you just need to set a
msg.argument property to the value you want to pass to the function :-)
Regards,
Max

**Comment by Toby-Mills** [comment]
That works like a charm!
Thanks for your help Max!

**Comment by maxst001** [comment]
Great!
You're welcome!
